apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: tcp-client
    port: {{ .Values.port.client }}
    protocol: TCP
    targetPort: tcp-client
  - name: http-admin
    port: {{ .Values.port.admin }}
    protocol: TCP
    targetPort: http-admin
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
