apiVersion: v2
appVersion: "1.83.14"
description: Helm chart for deploying the LiteLLM proxy
name: litellm
version: 0.0.2
type: application
icon: "https://storage.googleapis.com/zopdev-blog-resources/1/files/originals/20260716/litellm-logo-square.png"
maintainers:
  - name: ZopDev
    url: zop.dev
dependencies:
  - name: postgres
    version: 0.0.14
    repository: https://helm.zop.dev
    condition: postgres.enabled
annotations:
  type: application
