replicaCount: 1

version: "v0.0.1"

imagePullSecrets: []

service:
  type: ClusterIP
  port: 4242

resources:
  requests:
    memory: "1000Mi"
    cpu: "500m"
  limits:
    memory: "2000Mi"
    cpu: "1000m"

diskSize: "10Gi"

terminationGracePeriodSeconds: 90

zookeeper:
  replicaCount: 1
  diskSize: "10Gi"
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
