{{- $secretName := printf "%s-postgres-root-secret" .Release.Name }}
{{- $replicaSecretName := printf "%s-postgres-replication-secret" .Release.Name }}

{{/* Generate a strong root password only if not already set */}}
{{- $generatedRootPassword := printf "%s%s%s" (randAlpha 4) (randNumeric 4) (randAlpha 4 | upper) }}
{{- $generatedReplicaPassword := printf "%s%s%s" (randAlpha 4) (randNumeric 4) (randAlpha 4 | upper) }}

{{- $rootPassword := $generatedRootPassword }}
{{- $replicaPassword := $generatedReplicaPassword }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{- if .Release.IsInstall }}
  postgres-password: {{ $rootPassword | b64enc }}
    {{ else }}
  postgres-password: {{ index (lookup "v1" "Secret" .Release.Namespace $secretName ).data "postgres-password" }}
    {{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $replicaSecretName }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{- if .Release.IsInstall }}
  replicationpassword: {{ $replicaPassword | b64enc }}
    {{ else }}
  replicationpassword: {{ index (lookup "v1" "Secret" .Release.Namespace $replicaSecretName ).data "replication-password" }}
    {{ end }}