{{- if .Values.replica.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres-replica
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/part-of: postgres
    app: {{ $.Release.Name }}-postgres-replica
spec:
  replicas: {{ .Values.replica.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/part-of: postgres
      app: {{ $.Release.Name }}-postgres-replica
  serviceName: {{ $.Release.Name }}-postgres-replica
  updateStrategy:
    type: {{ .Values.updateStrategy.type }}
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: postgres
        app: {{ $.Release.Name }}-postgres-replica
    spec:
      containers:
        - name: postgres-replica
          image: "postgres:{{ .Values.version }}"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: {{ .Values.replica.resources.requests.memory }}
              cpu: {{ .Values.replica.resources.requests.cpu}}
            limits:
              memory: {{ .Values.replica.resources.limits.memory }}
              cpu: {{ .Values.replica.resources.limits.cpu }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-postgres-root-secret
                  key: postgres-password
            - name: PGDATA
              value: "/var/lib/postgresql/data/db/"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "md5"
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
            - name: POSTGRES_REPLICATION_MODE
              value: "replica"
            - name: POSTGRES_REPLICATION_USER
              value: "repl_user"
            - name: POSTGRES_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-postgres-replication-secret
                  key: replication-password
            - name: POSTGRES_PRIMARY_HOST
              value: "{{ $.Release.Name }}-postgres"
            - name: POSTGRES_PRIMARY_PORT
              value: "5432"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - "postgres"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - "postgres"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: {{ $.Release.Name }}-replica-persistent-storage
              mountPath: /var/lib/postgresql/data
              subPath: data
  volumeClaimTemplates:
    - metadata:
        name: {{ $.Release.Name }}-replica-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.replica.diskSize }}
{{- end }}