apiVersion: v1
kind: Service
metadata:
  name: {{ include "opentsdb.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opentsdb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "opentsdb.selectorLabels" . | nindent 4 }}
