apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "opentsdb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opentsdb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "opentsdb.fullname" . }}-headless
  selector:
    matchLabels:
      {{- include "opentsdb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opentsdb.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext: {}
      volumes:
        - name: config-opentsdb
          configMap:
            name: {{ include "opentsdb.fullname" . }}-config
            items:
              - key: opentsdb.conf
                path: opentsdb.conf
        - name: config-hbase
          configMap:
            name: {{ include "opentsdb.fullname" . }}-config
            items:
              - key: hbase-site.xml
                path: hbase-site.xml
      containers:
        - name: opentsdb
          image: "zopdev/opentsdb:{{ .Values.version }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4242
              protocol: TCP
          volumeMounts:
            - name: opentsdb-data
              mountPath: /data/hbase
            - name: config-opentsdb
              mountPath: /etc/opentsdb/opentsdb.conf
              subPath: opentsdb.conf
            - name: config-hbase
              mountPath: /opt/hbase/conf/hbase-site.xml
              subPath: hbase-site.xml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: opentsdb-data
        labels:
          {{- include "opentsdb.labels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.diskSize }}
