{{- range $index, $service := .Values.services }}
apiVersion: v1
kind: Pod
metadata:
  name: clickhouse-init-{{ $.Release.Name }}-{{ $service.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  containers:
    - name: clickhouse-init-role
      image: clickhouse/clickhouse-server:{{ $.Values.version }}
      command: ["clickhouse-client"]
      args:
        - "--host"
        - "{{ $.Release.Name }}-clickhouse"
        - "--port"
        - "9000"
        - "--user"
        - "default"
        - "--password"
        - "$(DEFAULT_PASSWORD)"
        - "--queries-file"
        - "/etc/config/db-init.sql"
      env:
        - name: DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $.Release.Name }}-clickhouse-default-secret
              key: default-password
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/config
  volumes:
    - name: secret-volume
      secret:
        secretName: {{ $.Release.Name }}-{{ $service.name }}-init-script
  restartPolicy: OnFailure
---
{{- end }}
