{{- $secretName := printf "%s-clickhouse-default-secret" .Release.Name }}

{{/* Generate a strong password for the default user only if not already set */}}
{{- $generatedPassword := printf "%s%s%s" (randAlpha 4) (randNumeric 4) (randAlpha 4 | upper) }}

{{- $defaultPassword := $generatedPassword }}

{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Release.IsInstall }}
  default-password: {{ $defaultPassword | b64enc }}
  {{- else if $secret }}
  default-password: {{ index $secret.data "default-password" }}
  {{- else }}
  default-password: {{ $defaultPassword | b64enc }}
  {{- end }}
