image: "solr:8.4"

resources:
  requests:
    memory: "1Gi"
    cpu: "100m"
  limits:
    memory: "2Gi"
    cpu: "1"

securityContext:
  runAsUser: 1001
  fsGroup: 1001

host:   test-solr-service-123.971a9e0f-595c-444b-a826-eabc8d6db79b.zop.dev

tlsHost:  '*.971a9e0f-595c-444b-a826-eabc8d6db79b.zop.dev'

diskSize:

services:
