apiVersion: v2
appVersion: "1.0"
description: Helm chart for deploying clickhouse datastore
name: clickhouse
version: 0.0.1
icon: "https://avatars.githubusercontent.com/u/54801242?s=200&v=4"
maintainers:
  - name: ZopDev
    url: zop.dev
annotations:
  type: datasource
